Category
VlasenkoYevhenii/book-store-app pull request #10
Opened 2024-05-13 15:34 UTC by VlasenkoYevhenii

2024-05-13 20:31 UTC, ReamFOX approved these changes
LGTM. Just a tiny comment. And you probably have here too many changes not related to the straight to the task.

2024-05-15 11:29 UTC, d1sam requested changes
Good job, but there are some changes, that should be done according to my comments.

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/controller/CategoryController.java
> +                description = "Add new category to the DB(ADMIN only")
```suggestion
                description = "Add new category to the DB(ADMIN only)")
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ADMIN')")
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
and in another places

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
```suggestion
    @PreAuthorize("hasRole('ROLE_ADMIN')")
    @ResponseStatus(value = HttpStatus.NO_CONTENT)
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/dto/category/CategoryRequestDto.java
> +    private String description;
what about max length of description?

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/mapper/BookMapper.java
> +        }
```suggestion
          if (book.getCategories() != null) {
      bookDto.setCategoryIds(book.getCategories().stream()
        .map(Category::getId)
        .collect(Collectors.toSet()));
    }
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/mapper/BookMapper.java
> +        }
let's use streams where it's possible

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/model/Book.java
> +            inverseJoinColumns = @JoinColumn(name = "category_id"))
```suggestion
            inverseJoinColumns = @JoinColumn(name = "category_id"))
     @ToString.Exclude
  @EqualsAndHashCode.Exclude
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/model/Category.java
> +    private String name;
```suggestion
    @Column(nullable = false)
    private String name;
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/model/Category.java
> +    private boolean isDeleted;
```suggestion
    private boolean isDeleted = false;
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/repository/book/BookRepository.java
>  public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```suggestion
@Repository
public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/repository/category/CategoryRepository.java
> +public interface CategoryRepository extends JpaRepository<Category, Long> {
```suggestion
@Repository
public interface CategoryRepository extends JpaRepository<Category, Long> {
```

2024-05-15 11:29 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-create-books-categories-table.yaml
> +                    references: categories(id)
```suggestion
                    references: categories(id)
                    
```

2024-05-15 11:29 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-05-15 11:29 UTC, d1sam commented on src/main/java/com/example/bookstoreapplication/service/category/CategoryServiceImpl.java
> +        return repository.findAll().stream().map(mapper::toDto).toList();
```suggestion
        return repository.findAll().stream().map(mapper::toDto).toList();
```
let's map all categories in the `CategoryMapper`

2024-05-15 11:53 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/controller/CategoryController.java
> +    @PreAuthorize("hasRole('ROLE_ADMIN')")
When using the @PreAuthorize annotation with roles, you should match the string that is returned by the getAuthority() method of your Role class.
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/39b6b1ab-7b5c-4777-863d-feeb2fb1cc2d)

2024-05-15 12:04 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/repository/book/BookRepository.java
>  public interface BookRepository extends JpaRepository<Book, Long>, JpaSpecificationExecutor<Book> {
No need for this annotation as Spring automatically interpreters JpaRepository extending interface as a bean

2024-05-15 12:31 UTC, andrii-hoienko approved these changes
Good job!

2024-05-16 05:59 UTC, merged