Add shopping cart model
VlasenkoYevhenii/book-store-app pull request #11
Opened 2024-05-16 14:19 UTC by VlasenkoYevhenii

2024-05-17 06:50 UTC, TonyH277 requested changes
Good job! Consider fetching only the necessary data from the DB.

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
```suggestion
    @PreAuthorize("hasRole('USER')")
```

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/controller/ShoppingCartController.java
> +                                                      CartItemUpdateDto updateDto) {
```suggestion
                                                      @RequestBody CartItemUpdateDto updateDto) {
```

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/dto/shoppingcart/ShoppingCartRequestDto.java
> +}
i think you don't need this class

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
Many users could have the same shopping cart?

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/model/ShoppingCart.java
> +    @OneToMany(fetch = FetchType.EAGER, mappedBy = "shoppingCart")
it's better to fetch only necessary inforamtion, i think it's better to leave fetchType to lazy and use join fetch EntityGraph annotation

2024-05-17 06:50 UTC, TonyH277 commented on src/main/java/com/example/bookstoreapplication/model/User.java
> +@Data
i think user should have Entity annotation

2024-05-17 07:01 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/a706fdde-804d-4eef-a235-beccbd650a78)

2024-05-17 07:02 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/04c0e406-5456-43aa-a038-bcc755c9c344)

2024-05-17 07:10 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/dto/shoppingcart/ShoppingCartRequestDto.java
> +}
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/5673fdac-da10-4adb-8f58-6c76e69d521a)
I think I do, 'cause it's the easiest way to handle the request body .

2024-05-17 07:11 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/model/CartItem.java
> +    @ManyToOne(fetch = FetchType.LAZY)
It's the CartItem class, not the ShoppingCart=)

2024-05-17 07:12 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/model/User.java
> +@Data
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/25064501-5ace-4976-9ac0-bf3c3d332763)
there is @Entity

2024-05-17 07:45 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/dto/shoppingcart/ShoppingCartRequestDto.java
> +}
valid)

2024-05-20 07:39 UTC, karma-o commented
Let's not commit each several lines of code, think of commits as stages of your development e.g: 
* added a repository with service methods 
* integrated those service methods into other services
* fixed some bug
* added endpoints for that service
* final clean ups

And that's it. Because 3 pages worth of commits is just to much :sweat_smile: 
You can also rebase this branch onto the last main(if all prev tasks are already merged) to rewrite the history and it'll look a bit better

2024-05-20 08:12 UTC, karma-o requested changes
Nice! Take a look at several suggestions

2024-05-20 08:12 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/security/JwtUtil.java
> +            throw new JwtException(VALIDATION_EXCEPTION_MSG, e);
I think it would be better to return false and log the ex that we catch

2024-05-20 08:12 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/cartitem/CartItemServiceImpl.java
> +        });
if we would want to add any more logic to that in the future, that lambda body will grow overtime, lets not put the main flow inside some other function, and do a check `if empty - throw ex`
Also you just ignore it if it does not exist, and will return 200 status anyway, which is not good

2024-05-20 08:12 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/shoppingcart/ShoppingCartServiceImpl.java
> +        shoppingCart.getCartItems().remove(cartItem);
you do not have an overriden `equals()` for cartItem, and `remove()` works using equals

2024-05-20 08:12 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/shoppingcart/ShoppingCartServiceImpl.java
> +        itemRepository.delete(cartItem);
you can set `orphanRemoval = true` for a set of cartItems in shopping cart model, to avoid manual deletion of removed cartItems

2024-05-20 08:12 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/shoppingcart/ShoppingCartServiceImpl.java
> +    public void removeBookFromCart(Long userId, Long cartItemId) {
```suggestion
    public void removeItemFromCart(Long userId, Long cartItemId) {
```

2024-05-20 08:18 UTC, VlasenkoYevhenii commented on .gitignore
> +liquibase.properties
because default location for this file is root so liquibase finds it automatically (don't even know how it works, but it works easier with this file in root folder)

2024-05-21 08:03 UTC, karma-o approved these changes
Looks good!

2024-05-21 08:15 UTC, merged