Book and category test added
VlasenkoYevhenii/book-store-app pull request #15
Opened 2024-05-27 12:32 UTC by VlasenkoYevhenii

![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/37f772ab-0c32-4a7d-9825-aa98c5a02c24)

2024-05-27 15:25 UTC, DmytroHadiuchko approved these changes
It looks good, but it seems to me that it too much hardcoding
you have the same situation with IDs, check it

2024-05-27 15:25 UTC, DmytroHadiuchko commented on src/test/java/com/example/bookstoreapplication/service/BookServiceImplTest.java
> +                .setCoverImage("https://example.com/book3-cover-image.jpg");
it seems to me that there is a lot of hardcoding here, maybe it's would be better to move it as constant

2024-05-27 15:25 UTC, DmytroHadiuchko commented on src/test/java/com/example/bookstoreapplication/service/CategoryServiceImplTest.java
> +        categoryRequestDto.setDescription("Fictional books");
you reuse name and description, maybe would be better move it to a constant

2024-06-03 07:40 UTC, karma-o requested changes
Missing integrational API controller tests with the use of test containers, let's add them for book and category controllers, and check other comments as well

2024-06-03 07:40 UTC, karma-o commented on .env
> +DEBUG_PORT=5005
better to not push that file

2024-06-03 07:40 UTC, karma-o commented on src/test/java/com/example/bookstoreapplication/service/BookServiceImplTest.java
> +    void saveBook_ValidBookRequest_ReturnBookDto() {
can we add some negative test cases for save method?

2024-06-03 07:40 UTC, karma-o commented on src/test/java/com/example/bookstoreapplication/service/BookServiceImplTest.java
> +        verify(bookRepository, times(ONE_TIME)).save(theHobbit);
```suggestion
        verify(bookRepository, once()).save(theHobbit);
```

2024-06-03 07:40 UTC, karma-o commented on src/test/java/com/example/bookstoreapplication/service/CategoryServiceImplTest.java
> +        categoryRequestDto.setDescription("Fictional books");
agree

2024-06-03 07:40 UTC, karma-o commented on src/test/java/com/example/bookstoreapplication/service/CategoryServiceImplTest.java
> +    }
again, can we add some negative cases, where service methods can throw us an exception as a response to some invalid input

2024-06-03 07:40 UTC, karma-o commented on src/test/java/com/example/bookstoreapplication/service/BookServiceImplTest.java
> +    void findBookById_ValidBookId_ReturnBookDto() {
where we have a `... by id` we can mock repo method that returns empty Optional and verify the behavior of our method in such cases, same for category tests

2024-07-03 14:32 UTC, VlasenkoYevhenii commented
![Screenshot_3](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/be0f9151-f4df-4e75-92c9-b24361927ef1)

2024-07-04 09:00 UTC, karma-o approved these changes
Looks very good!

2024-08-26 12:15 UTC, merged