Readme
VlasenkoYevhenii/book-store-app pull request #16
Opened 2024-05-28 16:07 UTC by VlasenkoYevhenii

2024-05-30 07:37 UTC, karma-o requested changes
Looks nice, take a look at a few comments

2024-05-30 07:37 UTC, karma-o commented on README.md
> +- Clone the repo, run `mvn clean package` and run it in IDE.
tell about the docker, about how to run with docker, about what technologies I need to run in IDE, that I need a database to run in the IDE, that I need to add ENV variables to run the application in both ways, give examples

2024-05-30 07:37 UTC, karma-o commented on README.md
> +# Installation
add a usage guide section after that, where you can tell about the auth and how does it work in your app, how to register, where to get the token, also add admin credentials to readme, so that a visitor of your project could also test admin-only endpoints, it's a demonstration project after all :)

2024-05-30 07:37 UTC, karma-o commented on README.md
> +## Endpoints
it's nice to a have a list here, but that is basically duplicated information from the swagger, and it is not clickable, let's have it here as it is, but also add a link to postman collection and a link to the swagger

2024-05-30 07:37 UTC, karma-o commented on README.md
> +```
this looks more of a usage guide section, then the list of endpoints

2024-05-30 07:37 UTC, karma-o commented on README.md
you can also add a link to your linked-in and a deployed project when you'll have them later on

2024-06-07 09:12 UTC, karma-o approved these changes
Really good job! Just a few more suggestions from me

2024-06-07 09:12 UTC, karma-o commented on README.md
may also be nice to have some challenges and their solutions section nad a video presentation with live comments on how your app works

2024-06-07 09:12 UTC, karma-o commented on README.md
> +- `POST /api/auth/registration` - [register a new user](https://www.postman.com/api-test-3019/workspace/bookstroe-managemet-public/request/31607463-de42cc79-9890-4501-8415-8cad8c37f6ce?action=share&c
let's elaborate a bit on how do these endpoints work, and where to put this token, also add admin and simple user credentials here, so that we can test **all** of the endpoints

2024-06-07 09:12 UTC, karma-o commented on README.md
> +    <img src="images/readme_footer_image.gif" alt="Footer Image">
:smile: :+1:

2024-06-27 13:11 UTC, VlasenkoYevhenii commented on README.md
> +    <img src="images/readme_footer_image.gif" alt="Footer Image">
😄

2024-06-29 11:45 UTC, merged