Book dto, Mapstruct
VlasenkoYevhenii/book-store-app pull request #2
Opened 2024-04-20 18:32 UTC by VlasenkoYevhenii

2024-04-21 09:39 UTC, DmytroHadiuchko requested changes
Good job! It looks good, I left a few minor comments

2024-04-21 09:39 UTC, DmytroHadiuchko commented on src/main/java/com/example/bookstoreapplication/BookStoreApplication.java
> +    private final BookMapper mapper;
I'm not sure, but I don't think that we need these fields here

2024-04-21 09:39 UTC, DmytroHadiuchko commented on src/main/resources/application.properties
>  spring.datasource.password=715914qQ()
don't push to remote repository your credentials

2024-04-21 13:19 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/BookStoreApplication.java
> +    private final BookMapper mapper;
These are obsolete from testing, thanks for noticing!)

2024-04-21 13:50 UTC, DmytroHadiuchko approved these changes

2024-04-22 08:56 UTC, karma-o approved these changes
Only left a minor comment, GJ!

2024-04-22 08:56 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/repository/BookRepositoryImpl.java
>          }
let's add catch blocks for general `Exception` in case we encounter any problem

2024-04-22 11:22 UTC, merged