Spring Data Jpa
VlasenkoYevhenii/book-store-app pull request #3
Opened 2024-04-23 14:11 UTC by VlasenkoYevhenii

2024-04-23 15:00 UTC, k0sm0naft requested changes
Needed few changes.

2024-04-23 15:00 UTC, k0sm0naft commented on src/main/java/com/example/bookstoreapplication/controller/BookController.java
> +    @PutMapping("/{id}")
You can add response status.

2024-04-23 15:00 UTC, k0sm0naft commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
Primary Key by default is NOT NULL
```suggestion
```

2024-04-23 15:00 UTC, k0sm0naft commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    unique: true
Why unique? If author write few books, we can't add them.
Better add `nullable: false` here.

2024-04-23 15:00 UTC, k0sm0naft commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +databaseChangeLog:
If you add constrains, batter, give them names.

2024-04-23 15:00 UTC, k0sm0naft commented on src/main/java/com/example/bookstoreapplication/service/BookServiceImpl.java
> +        Book book = mapper.toModel(dto);
You cant add or update book with isbn that already soft-deleted.

2024-04-24 06:06 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/service/BookServiceImpl.java
> +        Book book = mapper.toModel(dto);
yep, and it won't.

2024-04-24 15:29 UTC, andrii-hoienko approved these changes
Good job!

2024-04-24 15:29 UTC, andrii-hoienko commented on src/main/resources/db/changelog/changes/01-create-book-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```

2024-04-24 15:29 UTC, andrii-hoienko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-book-table.yaml
```suggestion
      file: db/changelog/changes/01-create-book-table.yaml
      
```

2024-04-25 07:11 UTC, merged