Global exception handler
VlasenkoYevhenii/book-store-app pull request #5
Opened 2024-04-30 08:36 UTC by VlasenkoYevhenii

2024-04-30 09:20 UTC, MolchanovAlexander approved these changes
Good work!

2024-05-01 13:15 UTC, andrii-hoienko requested changes
Good job, but some improvements required

2024-05-01 13:15 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapplication/exception/CustomGlobalExceptionHandler.java
> +    }
Are you sure that on EntityNotFoundException we should throw BAD_REQUEST?

2024-05-01 13:15 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapplication/exception/CustomGlobalExceptionHandler.java
> +        body.put(ERROR, errors);
Why only error is defined here?

2024-05-01 13:15 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapplication/controller/BookController.java
> +@Validated
I believe you should add Valid annotation in specific method to make validation work

2024-05-01 13:15 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapplication/dto/CreateBookRequestDto.java
>      private String description;
Please add some more validation rules, for example, ISBN definitely should not be empty

2024-05-01 13:15 UTC, andrii-hoienko commented on src/main/java/com/example/bookstoreapplication/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
Are you sure that on DataProcessingException we should throw BAD_REQUEST?

2024-05-01 15:13 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/dto/CreateBookRequestDto.java
>      private String description;
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/f77c0851-d64b-4c60-afcf-48fd9a5cee1a)
There are some validations for all the mandatory fields

2024-05-01 15:31 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.BAD_REQUEST);
It was supposed for only EntityNotFoundException, but there is a better HTTP status even for this one =)

2024-05-01 15:34 UTC, VlasenkoYevhenii commented on src/main/java/com/example/bookstoreapplication/exception/CustomGlobalExceptionHandler.java
> +        body.put(ERROR, errors);
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/159646520/1b4256b7-39d3-458f-8d05-c41636171e73)
If I get it right, not only error is defined

2024-05-02 09:43 UTC, merged