Spring boot security
VlasenkoYevhenii/book-store-app pull request #8
Opened 2024-05-10 09:49 UTC by VlasenkoYevhenii

2024-05-10 14:40 UTC, MolchanovAlexander approved these changes
GJ

2024-05-10 14:40 UTC, MolchanovAlexander commented on src/main/java/com/example/bookstoreapplication/security/SecurityConfig.java
> +                        auth.requestMatchers("/api/auth/**", "/swagger-ui/**")
I think your swagger don't work without  additional "/v3/api-docs/**".

2024-05-14 07:49 UTC, karma-o requested changes
GJ, Only some minor comments

2024-05-14 07:49 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/fieldvalidator/FieldMatchValidator.java
> +            return false;
I'd rather throw re-throw some exception here instead of false, because it is gonna be our fault as a programmer if we put some non existing field as a parameter to the annotation

2024-05-14 07:49 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/fieldvalidator/FieldMatchValidator.java
> +                    || firstValue != null && firstValue.equals(secondValue);
just use `Objects.equals()` instead

2024-05-14 07:49 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/user/UserServiceImpl.java
> +        user = userRepository.findByEmail(email).orElse(null);
you do not need this var `user`, this whole method can be inlined. I do not like this construction `.orElse(null)` you are returning a boolean so you could have just used `.isPresent()`. or we can just use `repo.existsByEmail(email)` to not even work with Optional, and that would be a bit more efficient since we do not need to fetch the actual user data

2024-05-14 07:49 UTC, karma-o commented on src/main/java/com/example/bookstoreapplication/service/user/UserServiceImpl.java
> +        }
it is nice that you have extracted a condition here, but we can extract this whole part of code into some `void checkExistanceByEmail(email);`

2024-05-14 07:49 UTC, karma-o commented on src/main/resources/liquibase.properties
> +driver=com.mysql.cj.jdbc.Driver
do we really need this file? I think we can just put all those properties int a general `application.properties`

2024-05-14 08:04 UTC, VlasenkoYevhenii commented on src/main/resources/liquibase.properties
> +driver=com.mysql.cj.jdbc.Driver
I need this file to perform Liquibase rollback operations

2024-05-14 09:11 UTC, karma-o commented
![image](https://github.com/VlasenkoYevhenii/book-store-app/assets/80981426/e73ba61b-5ab9-4ddf-ba1b-0db25ff5f9eb)
you have merged a remote `spring-boot-security` into `spring-boot-security` does not make much sense, does it?) Right now this PR base is main, so you should update your local main branch in IDEA, then merge `main` **into** `spring-boot-security`. We need to do that when you have a merge conflict in `spring-boot-security` PR or have some commits/changes that are visible here but actually were a part of the previous task

2024-05-14 09:14 UTC, karma-o approved these changes
GJ! take a look at the comment regarding the merge

2024-05-14 09:14 UTC, karma-o commented on .gitignore
> +src/main/resources/liquibase.properties
it is fine to push it if you really need it, I just thought that it is unnecessary

2024-05-14 11:10 UTC, merged